apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaurav-bankapp-deploy
  labels:
    app: gaurav-bankapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gaurav-bankapp-deploy
  template:
    metadata:
      labels:
        app: gaurav-bankapp-deploy
    spec:
      containers:
      - name: gaurav-bankapp-deploy
        image: gaurav4docker/gaurav-bankapp-deploy
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: gaurav-bankapp-np-service
  labels:
    app: gaurav-bankapp
spec:
  selector:
    app: gaurav-bankapp

  type: NodePort
  ports:
  - nodePort: 31030  
    port: 8082
    targetPort: 8082
